# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Mehmet
tagline:          'A blog'
url:              http://mehmet.me
baseurl:          ""

author:
  name:           'Mehmet'

paginate:         5