# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Mehmet Alkanlar
tagline:          'A blog'
description:      '.'
baseurl:          https://mehmeta.github.io/

author:
  name:           'Mehmet Alkanlar'

paginate:         5